apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  # NodePort permite acesso externo na porta 30082 (ex: http://localhost:30082/orders)
  type: NodePort
  selector:
    app: order-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
