apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  # NodePort permite tanto acesso interno via DNS (product-service:8081) quanto externo (localhost:30081)
  type: NodePort
  selector:
    app: product-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
