apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus-store
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  RABBITMQ_HOST: "nexus-rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  SHIPPING_SERVICE_URL: "http://nexus-shipping-service:8082"
  ZIPKIN_URL: "http://nexus-zipkin:9411"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  namespace: nexus-store
type: Opaque
stringData:
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
